### ISSUE TITLE
Multiple play function for Rhythm

### ISSUE THREAD

**Issue by NeonChicken** [mbreemhaar/thiliumbot#3]
Requesting multiple playlist through Rhythm bot takes a while as you have to input them one by one.

> **mplay** means Multiple Play(lists)
> **true** = !shuffle at the end (false = no !shuffle)
> **2** = amount of wait seconds in between (max. 10 maybe?)
> **link** = youtube/soundcloud link

Input:
$mplay true 2 link1 link2 link3

Output in #music:
!play link1
(wait 2 seconds)
!play link2
(wait 2 seconds)
!play link3
(wait 2 seconds)
!shuffle

**Comment by mbreemhaar** [comment]
Please write your issues in English so it's readable for anyone who wants to read this.
So essentially you want the bot to translate a more intuitive command into multiple Rhythm commands? At the moment, Thilium Bot cannot be in voice channels so Rhythm will probably not be able to know where to play the audio if we do it this way.

**Comment by NeonChicken** [comment]
Edited translation to English. But yeah that's the gist of it. 
I forgot that you have to be in a voice channel to input Rhythm commands! 
A right shame..
